MODEL:
  PRETRAINED: True
  PRETRAIN_PATH: '.../volo/checkpoints/d1_224_84.2.pth.tar'
  NAME: 'volo_d1'
  DEVICE_ID: ('0')
  OVERLAP: False

  DROP_PATH : 0.1
  DROP_OUT : 0.0
  ATT_DROP_RATE:  0.0


LOSS:
  TRIPLET_LOSS: True
  CENTER_LOSS: True
  CENTER_LOSS_WEIGHT: 0.0005



INPUT:
  SIZE_TRAIN:  [224, 224]
  SIZE_TEST: [224, 224]
  FLIP_PROB: 0.5
  RE_PROB: 0.5 
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  ROOT_DIR: ('...')

DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  IMS_PER_BATCH: 256

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 300
  BASE_LR: 0.002
  WARMUP_EPOCHS: 10
  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 50
  WEIGHT_DECAY:  0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  BIAS_LR_FACTOR: 2
  CENTER_LR: 0.5


OUTPUT_DIR: '...'


